#!/usr/bin/env python
import math
import random
import optparse
import os

from time import strftime 

outDir = '/data/cmszfs1/user/hiltbran/HGCAL_LDMX/PFCalEE/events/lheFiles/neutrons' 

usage = 'usage: %prog [options]'
parser = optparse.OptionParser(usage)
parser.add_option('-f', '--filename', dest='filename', help='lhe file name', default='neutrons')
parser.add_option('-n', '--nevts', dest='nevts', help='number of events', default=100, type=int)
parser.add_option('-e', '--energy', dest='energy', help='energy of events in GeV', default=4, type=float)
(opt, args) = parser.parse_args()

lhefile = open('%s/%d_%gGeV_%s.lhe'%(outDir,opt.nevts,opt.energy,opt.filename), 'w')
lhefile.write('<header>\n')
lhefile.write('This file contains primary neutrons with user chosen energy and (px,py,pz).\n')
lhefile.write('Do not edit this file manually.\n')
lhefile.write('File created on %s at %s\n'%(strftime('%Y-%m-%d'),strftime('%H:%M:%S')))
lhefile.write('</header>\n')

for i in range(0,opt.nevts):

    lhefile.write('<event>\n')
    
    #x = random.uniform(-10,10)
    #y = random.uniform(-10,10)

    phi = random.uniform(-math.pi/8, math.pi/8)
    theta = random.uniform(-math.pi/8, math.pi/8)

    px = math.sin(theta)*math.cos(phi)
    py = math.sin(theta)*math.sin(phi)
    pz = math.cos(theta)

    lhefile.write('2112 0 0 -50 %f %f %f %g\n'%(px,py,pz,opt.energy))

    lhefile.write('</event>\n')

lhefile.close()

